In [1]:
import numpy as np
import sympy as sp

In [3]:
#Q3
np.random.seed(16)
A = np.random.randint(0, 10, size=(5, 5))
sp.Matrix(A)
U,S,VT=np.linalg.svd(A)
print('U=',U)
print('S=',S)
print("VT=",VT)


U= [[-0.62022873 -0.17869049  0.69335619  0.28451816  0.14728421]
 [-0.48028758 -0.6114374  -0.49701693 -0.32605305  0.20526013]
 [-0.20129355 -0.17678468 -0.16118838  0.30809854 -0.89851081]
 [-0.2627987   0.32466975  0.25040979 -0.80964765 -0.32755461]
 [-0.52445964  0.67642497 -0.42842106  0.24956923  0.14683984]]
S= [22.13569524 10.48509677  4.80917542  3.29345679  0.31419103]
VT= [[-0.59418364 -0.5312117  -0.31792249 -0.27409378 -0.43423246]
 [ 0.21960172 -0.6166314   0.3921777   0.60864379 -0.21746308]
 [ 0.31274217  0.05519818  0.53579343 -0.58696177 -0.51724924]
 [ 0.19147408  0.41224729 -0.41834502  0.37026279 -0.69374545]
 [ 0.6813596  -0.40569099 -0.53201013 -0.26982712  0.12378393]]


In [4]:
USVT = np.dot(U, np.dot(np.diag(S), VT))

In [5]:
verification = np.allclose(USVT, A)

if verification:
    print("A equals the product of USVT.")
else:
    print("A does not equal the product of USVT.")

A equals the product of USVT.
